package minechem.init;

import java.util.Arrays;

import minechem.Minechem;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.ModMetadata;

public class ModGlobals {

	public static final String NAME = "Minechem";
	public static final String ID = "minechem";
	public static final String VERSION = "2.0.9a";

	public static final int TICKS_PER_SECOND = 20;
	public static final int TICKS_PER_MINUTE = TICKS_PER_SECOND * 60;
	public static final int TICKS_PER_HOUR = TICKS_PER_MINUTE * 60;
	public static final int TICKS_PER_DAY = TICKS_PER_HOUR * 24;
	public static final int TICKS_PER_WEEK = TICKS_PER_DAY * 7;
	public static final int GAS_PER_VIAL = 32; // Using mekanism this gets you 1024 hydrogen vs 1000 from a bucket of water.
	public static final String TEXT_MODIFIER = "\u00A7";
	public static final String TEXT_MODIFIER_REGEX = TEXT_MODIFIER + ".";

	public static class MetaData {
		/**
		 * Setup mod metadata
		 *
		 * @param metadata
		 * @return edited metadata object
		 */
		public static void preInit() {
			ModMetadata metadata = new ModMetadata();
			metadata.modId = ModGlobals.ID;
			metadata.name = ModGlobals.NAME;
			metadata.description = ModGlobals.NAME + " is a mod about chemistry, allowing you to research blocks and items, and then break them down into their base compounds and elements.";
			metadata.url = "https://minecraft.curseforge.com/projects/minechem";
			metadata.logoFile = "assets/" + ModGlobals.ID + "/logo.png";
			metadata.version = ModGlobals.VERSION;
			metadata.authorList = Arrays.asList("jakimfett", "TheRealp455w0rd");
			metadata.credits = "You can view a full list of contributors on github!";
			metadata.autogenerated = false;
			Minechem.metadata = metadata;
		}
	}

	public static class Sounds {
		private static final String SOUNDS_DIR = "sounds/" + ModGlobals.ID + "/";
		public static final String PROJECTOR = SOUNDS_DIR + "projector.ogg";
	}

	public static class Textures {
		public static final class IIcon {
			private static final String PREFIX = ModGlobals.ID + ":";

			public static final String POLYTOOL = PREFIX + "polytool";
			public static final String ATOMIC_MANIPULATOR = PREFIX + "AtomicManipulator";
			public static final String BLUEPRINT = PREFIX + "Blueprint";
			public static final String CHEMIST_JOURNAL = PREFIX + "ChemistJournal";
			public static final String FILLED_TESTTUBE = PREFIX + "filledTestTube";
			public static final String MOLECULE_PASS1 = PREFIX + "Molecule_Pass1";
			public static final String MOLECULE_PASS2 = PREFIX + "Molecule_Pass2";
			public static final String FILLED_MOLECULE = PREFIX + "filledMolecule";
			public static final String ELEMENT_GAS1 = PREFIX + "gas1";
			public static final String ELEMENT_GAS2 = PREFIX + "gas2";
			public static final String ELEMENT_GAS3 = PREFIX + "gas3";
			public static final String ELEMENT_GAS4 = PREFIX + "gas4";
			public static final String ELEMENT_GAS5 = PREFIX + "gas5";
			public static final String ELEMENT_GAS6 = PREFIX + "gas6";
			public static final String ELEMENT_GAS7 = PREFIX + "gas7";
			public static final String ELEMENT_LIQUID1 = PREFIX + "liquid1";
			public static final String ELEMENT_LIQUID2 = PREFIX + "liquid2";
			public static final String ELEMENT_LIQUID3 = PREFIX + "liquid3";
			public static final String ELEMENT_LIQUID4 = PREFIX + "liquid4";
			public static final String ELEMENT_LIQUID5 = PREFIX + "liquid5";
			public static final String ELEMENT_LIQUID6 = PREFIX + "liquid6";
			public static final String ELEMENT_LIQUID7 = PREFIX + "liquid7";
			public static final String ELEMENT_SOLID = PREFIX + "solid";
			public static final String PILL = PREFIX + "pill";
			public static final String LENS1 = PREFIX + "lens1";
			public static final String LENS2 = PREFIX + "lens2";
			public static final String LENS3 = PREFIX + "lens3";
			public static final String LENS4 = PREFIX + "lens4";
			public static final String DECOMPOSER_FRONT = PREFIX + "decomposerFront";
			public static final String DECOMPOSER = PREFIX + "decomposer";
			public static final String SYNTHESIS = PREFIX + "blockSynthesis";
			public static final String LEADEDCHEST = PREFIX + "leadedchest";
			public static final String MICROSCOPE_FRONT = PREFIX + "microscopeFront";
			public static final String MICROSCOPE = PREFIX + "blockMicroscope";
			public static final String BLUEPRINTPROJECTOR = PREFIX + "blockBlueprintProjector";
			public static final String FUSION1 = PREFIX + "fusion1";
			public static final String FUSION2 = PREFIX + "fusion2";
			public static final String BLUEPRINT1 = PREFIX + "blueprint1";
			public static final String BLUEPRINT2 = PREFIX + "blueprint2";
			public static final String DEFAULT = PREFIX + "default";
			public static final String URANIUM = PREFIX + "uraniumOre";
			public static final String BUCKET_EMPTY = PREFIX + "bucketEmpty";
			public static final String BUCKET_CONTENT = PREFIX + "bucketContent";
		}

		public static final class Gui {
			private static final String GUI_DIR = "textures/gui/";

			public static final String SPRITES = GUI_DIR + "allitems.png";

			public static final String TABLE_HEX = GUI_DIR + "tablegui.png";
			public static final String TAB_LEFT = GUI_DIR + "tab_left.png";
			public static final String TAB_RIGHT = GUI_DIR + "tab_right.png";
			public static final String DECOMPOSER = GUI_DIR + "chemicaldecomposergui.png";
			public static final String MICROSCOPE = GUI_DIR + "MicroscopeGUI.png";
			public static final String SYNTHESIS = GUI_DIR + "synthesisgui.png";
			public static final String FUSION = GUI_DIR + "fusionchambergui.png";
			public static final String PROJECTOR = GUI_DIR + "projectorgui.png";
			public static final String LEADED_CHEST = GUI_DIR + "leadedchestgui.png";
			public static final String JOURNAL = GUI_DIR + "chemistsjournalgui.png";
			public static final String VAT = GUI_DIR + "chemicalvatgui.png";
			public static final String PRINT = GUI_DIR + "printgui.png";
			public static final String POLYTOOL = GUI_DIR + "polytool.png";
			public static final String FISSION = GUI_DIR + "fissiongui.png";
			public static final String DECOMPOSER_NEI = GUI_DIR + "ChemicalDecomposerGUINEI.png";
			public static final String TANK = GUI_DIR + "fluidtank.png";
		}

		//For block-break particles
		public static final class Sprite {

			public static final ResourceLocation MICROSCOPE = new ResourceLocation(ModGlobals.ID, "sprite/microscope");
			public static final ResourceLocation SYNTHESIZER = new ResourceLocation(ModGlobals.ID, "sprite/synthesizer");
			public static final ResourceLocation DECOMPOSER = new ResourceLocation(ModGlobals.ID, "sprite/decomposer");
			public static final ResourceLocation BLUEPRINT_PROJECTOR = new ResourceLocation(ModGlobals.ID, "sprite/blueprint_projector");
			public static final ResourceLocation LEADED_CHEST = new ResourceLocation(ModGlobals.ID, "model/leadedchestmodel");
			public static final ResourceLocation FILLED_TUBE = new ResourceLocation(ModGlobals.ID, "items/filled_test_tube");

			public static final ResourceLocation[] LIQUID_STATES = new ResourceLocation[] {
					new ResourceLocation(ModGlobals.ID, "items/liquid1"),
					new ResourceLocation(ModGlobals.ID, "items/liquid2"),
					new ResourceLocation(ModGlobals.ID, "items/liquid3"),
					new ResourceLocation(ModGlobals.ID, "items/liquid4"),
					new ResourceLocation(ModGlobals.ID, "items/liquid5"),
					new ResourceLocation(ModGlobals.ID, "items/liquid6"),
					new ResourceLocation(ModGlobals.ID, "items/liquid7")
			};

			public static final ResourceLocation[] GAS_STATES = new ResourceLocation[] {
					new ResourceLocation(ModGlobals.ID, "items/gas1"),
					new ResourceLocation(ModGlobals.ID, "items/gas2"),
					new ResourceLocation(ModGlobals.ID, "items/gas3"),
					new ResourceLocation(ModGlobals.ID, "items/gas4"),
					new ResourceLocation(ModGlobals.ID, "items/gas5"),
					new ResourceLocation(ModGlobals.ID, "items/gas6"),
					new ResourceLocation(ModGlobals.ID, "items/gas7")
			};

			public static final ResourceLocation SOLID_STATE = new ResourceLocation(ModGlobals.ID, "items/solid");
			public static final ResourceLocation MOLECULE_TUBE = new ResourceLocation(ModGlobals.ID, "items/molecule");
			public static final ResourceLocation MOLECULE_PASS_1 = new ResourceLocation(ModGlobals.ID, "items/molecule_pass1");
			public static final ResourceLocation MOLECULE_PASS_2 = new ResourceLocation(ModGlobals.ID, "items/molecule_pass2");

			public static final ResourceLocation FLUID_STILL = new ResourceLocation(ModGlobals.ID, "blocks/fluid_still");
			public static final ResourceLocation FLUID_FLOW = new ResourceLocation(ModGlobals.ID, "blocks/fluid_flow");

		}

		public static final class Model {
			private static final String MODEL_DIR = "textures/model/";

			public static final String MICROSCOPE = MODEL_DIR + "microscopemodel.png";
			public static final String DECOMPOSER_ON = MODEL_DIR + "decomposermodelon.png";
			public static final String DECOMPOSER_OFF = MODEL_DIR + "decomposermodeloff.png";
			public static final String SYNTHESIS = MODEL_DIR + "synthesisermodel.png";
			public static final String PRINTER = MODEL_DIR + "rushmeadprinter.png";
			public static final String PROJECTOR_ON = MODEL_DIR + "projectormodelon.png";
			public static final String PROJECTOR_OFF = MODEL_DIR + "projectormodeloff.png";
			public static final String HAZMAT = MODEL_DIR + "hazmatarmor.png";
			public static final String CHEMICAL_STORAGE = MODEL_DIR + "chemicalstoragemodel.png";
			public static final String LEADED_CHEST = MODEL_DIR + "leadedchestmodel.png";
		}

		public static final class Icon {
			private static final String ICON_DIR = "textures/icons/";

			public static final String UNPOWERED = ICON_DIR + "i_unpowered.png";
			public static final String NO_RECIPE = ICON_DIR + "i_norecipe.png";
			public static final String POWER = ICON_DIR + "i_power.png";
			public static final String HELP = ICON_DIR + "i_help.png";
			public static final String PATREON = ICON_DIR + "i_patreon.png";
			public static final String FULL_POWER = ICON_DIR + "i_fullenergy.png";
			public static final String JAMMED = ICON_DIR + "i_jammed.png";
			public static final String NO_BOTTLES = ICON_DIR + "i_noBottles.png";
		}

	}

	public static class ModResources {
		public static final ResourceLocation SPRITES = new ResourceLocation(ModGlobals.ID, Textures.Gui.SPRITES);

		public static final class Icon {
			public static final ResourceLocation ENERGY = new ResourceLocation(ModGlobals.ID, Textures.Icon.POWER);
			public static final ResourceLocation FULL_ENERGY = new ResourceLocation(ModGlobals.ID, Textures.Icon.FULL_POWER);
			public static final ResourceLocation HELP = new ResourceLocation(ModGlobals.ID, Textures.Icon.HELP);
			public static final ResourceLocation PATREON = new ResourceLocation(ModGlobals.ID, Textures.Icon.PATREON);
			public static final ResourceLocation JAMMED = new ResourceLocation(ModGlobals.ID, Textures.Icon.JAMMED);
			public static final ResourceLocation NO_BOTTLES = new ResourceLocation(ModGlobals.ID, Textures.Icon.NO_BOTTLES);
			public static final ResourceLocation NO_RECIPE = new ResourceLocation(ModGlobals.ID, Textures.Icon.NO_RECIPE);
			public static final ResourceLocation NO_ENERGY = new ResourceLocation(ModGlobals.ID, Textures.Icon.UNPOWERED);
		}

		public static final class Tab {
			public static final ResourceLocation RIGHT = new ResourceLocation(ModGlobals.ID, Textures.Gui.TAB_RIGHT);
			public static final ResourceLocation LEFT = new ResourceLocation(ModGlobals.ID, Textures.Gui.TAB_LEFT);
			public static final ResourceLocation TABLE_HEX = new ResourceLocation(ModGlobals.ID, Textures.Gui.TABLE_HEX);
		}

		public static final class Gui {
			public static final ResourceLocation JOURNAL = new ResourceLocation(ModGlobals.ID, Textures.Gui.JOURNAL);
			public static final ResourceLocation POLYTOOL = new ResourceLocation(ModGlobals.ID, Textures.Gui.POLYTOOL);
			public static final ResourceLocation DECOMPOSER = new ResourceLocation(ModGlobals.ID, Textures.Gui.DECOMPOSER);
			public static final ResourceLocation NEI_DECOMPOSER = new ResourceLocation(ModGlobals.ID, Textures.Gui.DECOMPOSER_NEI);
			public static final ResourceLocation SYNTHESIS = new ResourceLocation(ModGlobals.ID, Textures.Gui.SYNTHESIS);
			public static final ResourceLocation PROJECTOR = new ResourceLocation(ModGlobals.ID, Textures.Gui.PROJECTOR);
			public static final ResourceLocation LEADED_CHEST = new ResourceLocation(ModGlobals.ID, Textures.Gui.LEADED_CHEST);
			public static final ResourceLocation MICROSCOPE = new ResourceLocation(ModGlobals.ID, Textures.Gui.MICROSCOPE);
			public static final ResourceLocation FISSION = new ResourceLocation(ModGlobals.ID, Textures.Gui.FISSION);
			public static final ResourceLocation FUSION = new ResourceLocation(ModGlobals.ID, Textures.Gui.FUSION);
			public static final ResourceLocation TANK = new ResourceLocation(ModGlobals.ID, Textures.Gui.TANK);
		}

		public static final class Model {
			public static final ResourceLocation PROJECTOR_OFF = new ResourceLocation(ModGlobals.ID, Textures.Model.PROJECTOR_OFF);
			public static final ResourceLocation PROJECTOR_ON = new ResourceLocation(ModGlobals.ID, Textures.Model.PROJECTOR_ON);
			public static final ResourceLocation DECOMPOSER_OFF = new ResourceLocation(ModGlobals.ID, Textures.Model.DECOMPOSER_OFF);
			public static final ResourceLocation DECOMPOSER_ON = new ResourceLocation(ModGlobals.ID, Textures.Model.DECOMPOSER_ON);
			public static final ResourceLocation LEADED_CHEST = new ResourceLocation(ModGlobals.ID, Textures.Model.LEADED_CHEST);
			public static final ResourceLocation MICROSCOPE = new ResourceLocation(ModGlobals.ID, Textures.Model.MICROSCOPE);
			public static final ResourceLocation SYNTHESIS = new ResourceLocation(ModGlobals.ID, Textures.Model.SYNTHESIS);
		}

	}

}
